In [10]:
# a is integer class
a = 10 

# b is float class
b = 10.0 

# c is string class
c = "this is string class" 

# d is list class
d = ["this", "is", "how to", "define", "a list"]

print("a : ", type(a), a)
print("b : ", type(b), b)
print("c : ", type(c), c)
print("d : ", type(d), d)

a :  <class 'int'> 10
b :  <class 'float'> 10.0
c :  <class 'str'> this is string class
d :  <class 'list'> ['this', 'is', 'how to', 'define', 'a list']


In [11]:
# -*- coding: utf-8 -*- 

# a is integer
a = 3

# b is float
b = 4.0

# bINT is integer
bINT = 4

# a plus b is float type
aPLUSb = a + b
print("a+b : ", type(aPLUSb), aPLUSb)

# a x b is float type
aMULb = a * b
print("a*b : ", type(aMULb), aMULb)

# a / b is float type
aDIVb = a / b
print("a/b : ", type(aDIVb), aDIVb)

# (*NOTE) a / b_INT is float type 
aDIVbINT = a / bINT
print("a/b(int) : ", type(aDIVbINT), aDIVbINT)

# remainder when a / b 
aREMb = a % b
print("a%%b : ", type(aREMb), aREMb)

# a^b is float type. Note that a^b is incorrect form 
aPOWERb = a ** b
print("a^b : ", type(aPOWERb), aPOWERb)

import math # To use square root function

aSQRT = math.sqrt(a)
print("sqrt(a) : ", type(aSQRT), aSQRT)

a+b :  <class 'float'> 7.0
a*b :  <class 'float'> 12.0
a/b :  <class 'float'> 0.75
a/b(int) :  <class 'float'> 0.75
a%%b :  <class 'float'> 3.0
a^b :  <class 'float'> 81.0
sqrt(a) :  <class 'float'> 1.7320508075688772


In [13]:
# -*- coding: utf-8 -*- 
a = 1+3j
b = 1-3j
c = 5

# real/imaginary part of a (complex number)
aREAL = a.real
aIMAG = a.imag
print("Real part of a : ", aREAL)
print("Imaginary part of a : ", aIMAG)

# a plus b is complex type
aPLUSb = a + b
print("a+b : ", aPLUSb)

# a multiply b is complex type
aMULb = a * b
print("a*b : ", type(aMULb), aMULb)

# a divided by b is complex type
aDIVb = a / b
print("a/b : ", aDIVb)

# (1+3j)^5
aPOWERc = a ** c
print("a^c", aPOWERc)

import cmath # To use complex number square root function

# square root of a (1+3j)
# (*NOTE) square root of complex needs "cmath" package!
aSQRT = cmath.sqrt(a)
print("sqrt(a) : ", aSQRT)

# exp(a)
aEXP = cmath.exp(a)
print("exp^(a) : ", aEXP)

# log_10(a)
aLOG10 = cmath.log10(a)
print("log_10(a) : ", aLOG10)

# log_e(a)
aLOGe = cmath.log(a)
print("log_e(a) : ", aLOGe)

Real part of a :  1.0
Imaginary part of a :  3.0
a+b :  (2+0j)
a*b :  <class 'complex'> (10+0j)
a/b :  (-0.7999999999999999+0.6j)
a^c (316-12j)
sqrt(a) :  (1.442615274452683+1.0397782600555705j)
exp^(a) :  (-2.6910786138197937+0.383603953541131j)
log_10(a) :  (0.5+0.5424536865971469j)
log_e(a) :  (1.151292546497023+1.2490457723982544j)


In [14]:
# -*- coding: utf-8 -*- 
str1 = "Hello"
str2 = " World"

# you can add strings!
print("str1 + str2 : ", str1+str2)

# you can access strings first to 3th characters by index
print("0th-3rd of str1 : ", str1[0:3])

# -1 index means the last character
print("str1[-1] : ", str1[-1])

# you can multiply strings!  
print("str1*4 : ", str1*4)

str1 + str2 :  Hello World
0th-3rd of str1 :  Hel
str1[-1] :  o
str1*4 :  HelloHelloHelloHello


In [19]:
# a is 1-d list
a = [0, 0, 0, "string element"]

# b is 2d-list 3x3
b = [[1, 1, 1], [1, 2, 3], [4, 5, 6]]

print("a is : ", a)
print("b is : ", b)

import numpy as np

# c is 2d-array 3x3
c = np.array([[1, 2, 3],[3, 4, 5],[5, 6, 7]])

print("c is : ", c)
print("Shape of c is : ", np.shape(c))

# print 1st row 
print("1st row of c is : ", c[0])

# print 1st column
print("1st column of c is : ", c[:,0])

# print b+c array
print("b + c array is : ", b+c)

from numpy.linalg import inv
x = np.matrix([[2,3],[4,5]])
print("Matrix x is : ", x)

# print inverse matrix of x 
# (*NOTE) you can't get an inverse matrix of 2d-array or list (only matrix!)
print("Inverse matrix of x : ", inv(x))

# empty list
d = []

# append a list row by row
d.append([1,1,1])
d.append([1,2,3])
print("Shape of d is : ", np.shape(d))

# divide an array by 3
# (*NOTE) you CAN'T do this to list!!!
y = np.array([3, 6, 9, 12])
y = y/3.0

print("Matrix y is : ", y)

a is :  [0, 0, 0, 'string element']
b is :  [[1, 1, 1], [1, 2, 3], [4, 5, 6]]
c is :  [[1 2 3]
 [3 4 5]
 [5 6 7]]
Shape of c is :  (3, 3)
1st row of c is :  [1 2 3]
1st column of c is :  [1 3 5]
b + c array is :  [[ 2  3  4]
 [ 4  6  8]
 [ 9 11 13]]
Matrix x is :  [[2 3]
 [4 5]]
Inverse matrix of x :  [[-2.5  1.5]
 [ 2.  -1. ]]
Shape of d is :  (2, 3)
Matrix y is :  [1. 2. 3. 4.]


In [17]:
# -*- coding: utf-8 -*- 
a = [1,2,3,4]

# memory address of list a
print("Memory address of list a : ", id(a))

# is b copy of a? or a itself?
b = a
print("b = a : ", b)
print("Memory address of list b : ", id(b))

Memory address of list a :  1795157899272
b = a :  [1, 2, 3, 4]
Memory address of list b :  1795157899272


In [21]:
# -*- coding: utf-8 -*-
from copy import copy

a = [1,2,3,4]
print("a is : ", a)

# b is exactly a
b = a

# c is the COPIED a
c = copy(a)

# change 1st element of c
c[0] = "c[0] changed"

# check if a is gonna change
print("After c is changed\na : ", a)
print("b : ", b)
print("c : ", c)

# change 1st element of b
b[0] = "b[0] changed"

# check if a is gonna change
print("After b is changed\na : ", a)
print("b : ", b)
print("c : ", c)


a is :  [1, 2, 3, 4]
After c is changed
a :  [1, 2, 3, 4]
b :  [1, 2, 3, 4]
c :  ['c[0] changed', 2, 3, 4]
After b is changed
a :  ['b[0] changed', 2, 3, 4]
b :  ['b[0] changed', 2, 3, 4]
c :  ['c[0] changed', 2, 3, 4]


In [22]:
# -*- coding: utf-8 -*- 

# define a tuple by () 
# (*NOTE) list : [], tuple : ()
ex1 = ()
ex2 = ('a', 'b', ('ab', 'cd'))
physical_const = (3.141592, 1.38e-23, 1.05e-34)

# try to update tuple's first element
physical_const[0] = 3.1415    

TypeError: 'tuple' object does not support item assignment

In [27]:
# -*- coding: utf-8 -*- 

# append new dictionary key and value
# (*NOTE) "24" is string but 24 is int type!!!
human1 = dic = {'name':'sunPark', 'phone':'01011112222', 'birth': '0909'}   
human1["age"] = "24"

# print birth value of human1
print("Access to birth of human1 : ", human1["birth"])


# check if 'name' is in human1 dictionary
print("'name' in human1 : ", 'name' in human1)

# check if 'email' is in human1 dictionary
print("'email' in human1 : ", 'email' in human1)

Access to birth of human1 :  0909
'name' in human1 :  True
'email' in human1 :  False


In [29]:
# -*- coding: utf-8 -*- 
import numpy as np

# \t means makes a horizontal Tab space
data = input("you can write a sentence before : \t") 

print(type(data))

if float(data) is not np.isnan: # check if data is pure number
  data = float(data)
  # type casting to float
  print("INPUT is float ", type(data))
else:
  print("INPUT is not a number ", type(data))
  pass

<class 'str'>


ValueError: could not convert string to float: 

In [30]:
# -*- coding: utf-8 -*- 
a = [1,2,3,4,5, "name", "1e-4"]
b = 52
c = False

if c is True:
  print("c is True variable")
else:
  print("c is False variable")
  
if b < 54:
  print("b : %d is less than 54" %(b))
  # %d means int type variable
  b = b + 15
  # (*NOTE) b ++, b +=15 are invalid expressions
elif b > 56:
  # even if b becomes 67, this code doesn't run
  print("b : %d is more than 56" %(b))
else:
  print("b is 55 if b is int type")
  
if "birthday" in a:
  # you can search an element by using "in"
  print("birthday string is in list a")
elif "name" in a:
  print("name string is in list a")
else:
  print("I give up.") 

c is False variable
b : 52 is less than 54
name string is in list a


In [31]:
a = [1,2,3,4,5]
for val in a:
  # list a iteration
  print(val, end=" ")
  # print in one line
print()  
for idx, val in enumerate(a):
  # you can get index and element by using enumerate(list)
  print("idx : %d,val: %d" %(idx, val), end=" ")
print()
for val in range(10):
  # 0 to 9
  print(val, end=" ")
print()  
for val in range(2,10):
  # 2 to 9
  print(val, end=" ")
print()
for val in range(2, 10, 2):
  # 2 to 9 interval 2
  print(val, end=" ")

1 2 3 4 5 
idx : 0,val: 1 idx : 1,val: 2 idx : 2,val: 3 idx : 3,val: 4 idx : 4,val: 5 
0 1 2 3 4 5 6 7 8 9 
2 3 4 5 6 7 8 9 
2 4 6 8

In [32]:
# -*- coding: utf-8 -*- 
for val in range(0,10,0.5):
  # 0 to 9.9999 with interval 0.5
  print(val, end=" ")  

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
import numpy as np
a = np.arange(0.0, 10.0, 0.88)
for val in a:
    print(val, end=" ")
print()
b = np.linspace(0.0, 10.0, 11)
for val in b:
    print(val, end=" ")

0.0 0.88 1.76 2.64 3.52 4.4 5.28 6.16 7.04 7.92 8.8 9.68 
0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0

In [35]:
import numpy as np

# make a list with step size 0.88
a = np.arange(0.0, 10.0, 0.88)

for val in a:
    print(val, end=" ")



0.0 0.88 1.76 2.64 3.52 4.4 5.28 6.16 7.04 7.92 8.8 9.68

In [36]:
import numpy as np

# make a list with size 11
b = np.linspace(0.0, 10.0, 11)
for val in b:
    print(val, end=" ")

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0

In [37]:
# -*- coding: utf-8 -*- 
import numpy as np

while True:
  # inf. loop
  data = input("PLEASE INPUT NUMBER\t")
  if data.isnumeric():
    data = float(data)
    print("data is : %f" %(data))
    break
  else:
    print("WRONG INPUT!")   

WRONG INPUT!
WRONG INPUT!
WRONG INPUT!
WRONG INPUT!
data is : 20.000000


In [40]:
# -*- coding: utf-8 -*- 

wrong_ex = "string ipnida"

try:
    wrong_result = wrong_ex + 20

except:
    print("You just tried something wrong")



You just tried something wrong


In [41]:
# -*- coding: utf-8 -*- 

wrong_ex = "string ipnida"

try:
    wrong_result = wrong_ex + 20

except TypeError:
    print("You just tried TypeError")

You just tried TypeError


In [42]:
# -*- coding: utf-8 -*- 

wrong_ex = "string ipnida"

try:
    wrong_result = wrong_ex + 20

except EOFError:
    print("You just tried TypeError")

TypeError: can only concatenate str (not "int") to str

In [49]:
# -*- coding: utf-8 -*- 
from numpy import pi
# pi = 3.141592 선언보다 정확하고 멋있자너

class Pancake():
    # class 첫글자는 보통 대문자 시작
    def __init__(self, r, N, current, superconductor):
        # __init__()은 Pancake() 클래스를 만들자마자
        # 실행되는 함수. self의 매개변수는 필수니 까먹지 마세요
        # 지금 보면 self 외에 4개의 변수가 필요하므로
        # ex_pancake = Pancake(10, 20, 100, "YBCO") 처럼 객체 생성

        # Pancake 클래스 내부 변수 저장 
        self.r = r # 내경
        self.turns = N # 턴 수
        self.Iop = current # 전류
        self.material = superconductor # 물질

    def calculateB(self): 
        # 중심자장 계산 (대충하는거니 따지지 마셈)
        self.centerB = 4*pi*1e-7*self.turns*self.Iop/(2*pi*self.r)

        # 계산된 값을 결과로 내뱉고 싶으면 return을 굳이 그러고 싶지 않으면 안 해도 됨
        return self.centerB

# 실 사용 예제 
# Pancake() 객체 생성 
ex1 = Pancake(0.5, 15000, 250, "YBCO")

# ex1 팬케이크의 중심자장 계산 메소드 호출
ex1.calculateB()

# %.2f : 유효숫자 2개로 보여라 
print("Radius %.2f, Turns %d, Current %.2f of Pancake's Center B Field : %.2f [T]" 
    %(ex1.r, ex1.turns, ex1.Iop, ex1.centerB))


Radius 0.50, Turns 15000, Current 250.00 of Pancake's Center B Field : 1.50 [T]


In [53]:
# -*- coding: utf-8 -*- 
from numpy import pi

class Pancake():
    # class name usually starts with Capital letter
    def __init__(self, r, N, current, superconductor):
        # __init__(self) is the first method (like constructor)
        # "self" is necessary argument

        # To save variables
        self.r = r # radius of pancake [m]
        self.turns = N # number of turns [#]
        self.Iop = current # operating current [A]
        self.material = superconductor # material name

    def calculateB(self): 
        # center magnetic field calculation
        self.centerB = 4*pi*1e-7*self.turns*self.Iop/(2*pi*self.r)

        # return is not necessary
        return self.centerB

class Magnet(Pancake):
    # Magnet > Pancake
    def __init__(self, r, N, current, superconductor, num_P):
        # call Pancake's __init__()  
        super().__init__(r, N, current, superconductor)

        self.numPancakes = num_P # number of pancakes

    def calculateB(self):
        # Same method but different operation
        self.magnetB = super().calculateB()*self.numPancakes

        return self.magnetB

# example
ex_magnet = Magnet(0.5, 15000, 250, "YBCO", 4)
ex_magnet.calculateB()

print("Radius %.2f [m], Turns %d, Current %.2f [A] of %d Pancake Magnet's Center B Field : %.2f [T]" 
    %(ex_magnet.r, ex_magnet.turns, ex_magnet.Iop, ex_magnet.numPancakes, ex_magnet.magnetB))

Radius 0.50 [m], Turns 15000, Current 250.00 [A] of 4 Pancake Magnet's Center B Field : 6.00 [T]


In [58]:
# -*- coding: utf-8 -*- 
ex1 = [10, 5, 22, 0, -22, 0.5]

# using for - loop
for_out = []
for i in range(len(ex1)):
    for_out.append(i)
print("for_out : ", for_out)

# using list(range)
list_out = list(range(len(ex1)))
print("list_out : ", list_out)

#using lambda-map function
lambda_out = list(map(lambda x: x, range(len(ex1))))
print("lambda_out : ", lambda_out)

for_out :  [0, 1, 2, 3, 4, 5]
list_out :  [0, 1, 2, 3, 4, 5]
lambda_out :  [0, 1, 2, 3, 4, 5]


In [61]:
# -*- coding: utf-8 -*- 

# a = write mode (init position: end)
# r = read mode (init position: beginning)
# w = write mode (new file)
f = open("write.txt", "a")
for i in range(1, 11):
    # write a new line 
    data = "%dline\n" % i
    f.write(data)
f.close()

In [62]:
# -*- coding: utf-8 -*- 

# a = write mode (init position: end)
# r = read mode (init position: beginning)
# w = write mode (new file)
f = open("write.txt", "r")

data = f.readlines() # read all text
print("data type: ", type(data), "data size: ", len(data))
print(data)


data type:  <class 'list'> data size:  10
['1line\n', '2line\n', '3line\n', '4line\n', '5line\n', '6line\n', '7line\n', '8line\n', '9line\n', '10line\n']


In [4]:
# -*- coding: utf-8 -*- 

# a = write mode (init position: end)
# r = read mode (init position: beginning)
# w = write mode (new file)
f = open("write.txt", "r")
while True:
    line = f.readline()
    if not line: break
    print(line)
f.close()

1line

2line

3line

4line

5line

6line

7line

8line

9line

10line



In [5]:
from numpy import sqrt 
print("sqrt(3): " ,sqrt(3))

sqrt(3):  1.7320508075688772


In [6]:
import numpy as np
print("np.sqrt(3): " ,np.sqrt(3))

np.sqrt(3):  1.7320508075688772
