In [4]:
# -*- coding: utf-8 -*- 
import numpy as np 

arr1d = np.array([0, 1, 2])
print("Type : ", type(arr1d), " shape : ", arr1d.shape, " dimension : ", arr1d.ndim)

list1d = [0, 1, 2]
print("Type : ", type(list1d), " size : ", np.size(list1d))

Type :  <class 'numpy.ndarray'>  shape :  (3,)  dimension :  1
Type :  <class 'list'>  size :  3


In [7]:
arr1 = np.array([0, 1, 2])
arr2 = np.array([-1, 2, 3])

print("arr1+arr2 : ", arr1+arr2)

list1d = [0, 1, 2]

print("arr1+list1d : ", arr1+list1d)


arr1+arr2 :  [-1  3  5]
arr1+list1d :  [0 2 4]


In [14]:
arr2d = np.array([[0, 1], [2, 3]])
print("Type : ", type(arr2d), " shape : ", arr2d.shape, " dimension : ", arr2d.ndim)
print("arr2d : ", arr2d)

arrblank = np.zeros(shape=(3,2))
print("Type : ", type(arrblank), " shape : ", arrblank.shape, " dimension : ", arrblank.ndim)
print("arrblank : ", arrblank)

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print("a+b : ", a+b)
print("a-b : ", a-b)
print("a*b : ", a*b)
print("a@b(a dot b) : ", a@b)
print("np.dot(a,b) : ", np.dot(a,b))

Type :  <class 'numpy.ndarray'>  shape :  (2, 2)  dimension :  2
arr2d :  [[0 1]
 [2 3]]
Type :  <class 'numpy.ndarray'>  shape :  (3, 2)  dimension :  2
arrblank :  [[0. 0.]
 [0. 0.]
 [0. 0.]]
a+b :  [[ 6  8]
 [10 12]]
a-b :  [[-4 -4]
 [-4 -4]]
a*b :  [[ 5 12]
 [21 32]]
a@b(a dot b) :  [[19 22]
 [43 50]]
np.dot(a,b) :  [[19 22]
 [43 50]]


In [3]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 3], [2, 4]])

print("Element X Element - a*b(array) : ",a*b)

# ma = np.matrix([[1, 2], [3, 4]]) also possible

ma = np.mat(a)
mb = np.mat(b)

print("Matrix multiply - ma*mb(matrix) : ", ma*mb)

m1 = np.matrix([[1,2], [3,4]])
sum1 = np.sum(m1)

print("Sum of matrix - np.sum(m1) : ", sum1)
print("Inverse matrix - m1.I : ", m1.I)
print("Transpose matrix - m1.transpose() : ", m1.transpose())

Element X Element - a*b(array) :  [[ 1  6]
 [ 6 16]]
Matrix multiply - ma*mb(matrix) :  [[ 5 11]
 [11 25]]
Sum of matrix - np.sum(m1) :  10
Inverse matrix - m1.I :  [[-2.   1. ]
 [ 1.5 -0.5]]
Transpose matrix - m1.transpose() :  [[1 3]
 [2 4]]


In [7]:
import numpy as np 
arr = np.arange(0, 4*2*4)

print("arr : ")
print(arr)

# 1d -> [4, 2, 4]; row: 4, column: 2, depth: 4
v = arr.reshape([4,2,4]) 
print("v (arr.reshape([4, 2, 4])) : ")
print(v)
print("v.ndim : ", v.ndim)
print("v.sum : ", v.sum())

# axis=0 sum
res01=v.sum(axis=0) 
print("res01.shape : ", res01.shape)
print("res01 : ")
print(res01)

# axis=1 sum
res02=v.sum(axis=1)  
print("res02.shape : ", res02.shape)
print("res02 : ")
print(res02)

# axis=2 sum
res03=v.sum(axis=2)  
print("res03.shape : ", res03.shape)
print("res03 : ")
print(res03)


arr : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
v (arr.reshape([4, 2, 4])) : 
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
v.ndim :  3
v.sum :  496
res01.shape :  (2, 4)
res01 : 
[[48 52 56 60]
 [64 68 72 76]]
res02.shape :  (4, 4)
res02 : 
[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]
res03.shape :  (4, 2)
res03 : 
[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]
